### ISSUE TITLE
Document version strategy requirements for Aptible database Docker images

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#110]
cc: @aaw @jbergknoff

Now that we are tagging all Aptible database images according to their versions, I wanted to try to establish a set of requirements for compatibility within a given tag, which (when combined with each database's internal compatibility guarantees, or lack thereof) can completely determine our tagging strategy for each database type.

The approach I'm proposing can be summarized as "full backward compatibility" within a given tag, but here it is, spelled out:
- `RestartDatabase`: Any image revision with a given tag must be able to run a container with volumes mounted from any container started with an earlier revision of the same tag.
- `--client`: Any image revision with a given tag must be able to open a remote client to any container running an earlier version of the same tag.
- `--dump` and `--restore`: Any image revision with a given tag must be able to remotely dump from any container running an earlier revision of the same tag, or restore from a dump created by an earlier revision of the same tag.
- Replication: Any image revision with a given tag must be able to replicate (read-only?) from any container running an earlier revision of the same tag.

Here's what the above strategy would mean for our current supported database types. I've included the current tags (and individual revisions out in the wild), along with some references used to justify each decision.

| Database Type | Tag Level | Current Tags + Revisions | Compatibility References |
| --- | --- | --- | --- |
| PostgreSQL | PG "major" version | **9.4** (9.4.1, 9.4.2, 9.4.3) <br /> **9.3** (9.3.3, 9.3.4, 9.3.5, 9.3.6) | [Versioning policy](http://www.postgresql.org/support/versioning/) |
| MySQL | Release series number | **5.6** (5.6.19, 5.6.24, 5.6.25) | [Replication compatibility between versions](https://dev.mysql.com/doc/refman/5.0/en/replication-compatibility.html) <br /> [Choosing which version to install](https://dev.mysql.com/doc/refman/5.0/en/choosing-version.html) |
| MongoDB | Minor version | **2.6** (2.6.0, 2.6.8, 2.6.9, 2.6.10) | (e.g.) [Compatibility changes in 3.0](http://docs.mongodb.org/manual/release-notes/3.0-compatibility/) |
| Redis | Minor version | **2.8** (2.8.7, 2.8.8, 2.8.9, 2.8.17) | [(misc. mailing list threads)](https://groups.google.com/forum/#!forum/redis-db) |
| Elasticsearch | Minor version | **1.3** (1.3.2) <br /> **1.5** (1.5.2) | [Upgrading](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html) |
| CouchDB | Exact version? | **1.5.0** (1.5.0) | (none) |

@aaw and @jbergknoff - does this seem sane to you guys?

**Comment by aaw** [comment]
This is great, thanks in particular for doing all of the work on the matrix. 

What do you mean by replication in the final bullet point? Are you saying that if the database has any supported multi-node configuration, that configuration should always work with containers running the same tag, independent of versions within that tag? If so, I think that's totally reasonable.

**Comment by fancyremarker** [comment]
@aaw: I meant something different, but I think your constraint is better (and clearer) than mine.

I meant that if a database has a supported 1 leader-multiple followers configuration, then the follower containers must work with a leader running any earlier revision of the same tag (but not necessarily vice versa).

Like I said, I think your constraint is better, and should still work with the tag decisions outlined in the matrix above.

**Comment by fancyremarker** [comment]
Closing this for now. I don't think any support article is necessary to publish.
