### ISSUE TITLE
(Host-level) New Relic Docker support

### ISSUE THREAD

**Issue by steakchaser** [aptible/support#115]
New Relic just announced [GA support for Docker](https://blog.newrelic.com/2015/06/19/docker-monitoring-general-availability).  The only [additional setup instructions](https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration/enabling-new-relic-servers-docker) appear to be:
1. If a `docker` group doesn't already exist, create a new group named `docker`:
   `groupadd -r docker`
2. Add the `newrelic` user to the docker group with a command similar to:
   `usermod -a -G docker newrelic`
3. Restart Docker

I've tried this in my Docker file (incl re-built image from scratch) to ensure that the latest [New Relic Servers for Linux](https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration) was installed.

The expected result should be rolled-up container info under "Servers" on the APM Dashboard.  However, it still just shows the individual containers.

**Comment by fancyremarker** [comment]
Changed title from "New Relic Docker support"...

**Comment by fancyremarker** [comment]
This is implemented on our backend. For now, it can't be set automatically by customers or through our API, but please contact support@aptible.com to get set up.
