### ISSUE TITLE
Carry VHOSTs along with services when the service name changes

### ISSUE THREAD

**Issue by aaw** [aptible/support#120]
When you change the name of a service in the Procfile, that service loses its VHOSTs. In a lot of cases, it's tricky to figure out if the newly named service is supposed to be a renaming of the existing service (if the process definition changes, if more than one service's name changes, etc.) But if _only_ one service's name changes and the service definition stays the same, we could probably safely copy the existing VHOSTs across to the new service.

**Comment by wcpines** [comment]
Closing in favor of trello/cleaner issue mgmt
