### ISSUE TITLE
Reported in #public - needed an ssl config set to connect to postgres

### ISSUE THREAD

**Issue by gib** [aptible/support#129]
> in order to let my aptible app connect to my aptible database, i had to set ssl mode on:
> `aptible config:set PGSSLMODE=require --app $APP_HANDLE`
> without that, postgres would not allow the app to connect
> in case it matters, i'm using nodejs & express and connecting via the pg-promise library

I could see this going in quick start guides that use postgres (like here: https://github.com/aptible/support/blob/master/source/quickstart/ruby/rails.md#4-provision-and-connect-a-database), but looking for some guidance or a confirmation.

**Comment by gib** [comment]
After discussing with @sandersonet and @fancyremarker in slack, will add a trouble shooting article.

See: https://support.aptible.com/topics/troubleshooting/no-pg-hba-conf-entry-for-host/

search results for "ssl postgres" in Zendesk:
- sails (Node): https://aptible.zendesk.com/agent/tickets/685
- JDBC (Scala/Play): https://aptible.zendesk.com/agent/tickets/1142
- knex.js (Node): https://aptible.zendesk.com/agent/tickets/1013
- pgweb (GUI app): https://aptible.zendesk.com/agent/tickets/717

**Comment by wcpines** [comment]
Documented elsewhere
