### ISSUE TITLE
Add a doc for installing intermediate SSL certificates

### ISSUE THREAD

**Issue by gib** [aptible/support#164]
> We represent "certificate bundles" in the native OpenSSL format, which involves simply concatenating them together.
> 
> If you have each of your intermediate certs, you can run something like:
> 
> `cat YOUR_DOMAIN.crt TrustedRoot.crt > bundle.crt`
> 
> And then upload `bundle.crt` to Aptible. Your certificate issuer will have instructions on the order in which to concatenate these certificates (it's important), but in general, they need to go from most specific (your own certificate) to least specific (the certificate for the global trusted CA).

**Comment by gib** [comment]
For the doc:
- Test certificate chains with https://www.digicert.com/help/
- Be sure to update an existing cert or you can end up with two certs named the same thing

**Comment by fancyremarker** [comment]
@gib: Also, I made this Ruby script to properly order/check intermediate certs: https://gist.github.com/fancyremarker/569e37f373cbc2a138e5

There is probably a good single-page website that does the same thing. If not, we could create one. (Content marketing :100: )

**Comment by gib** [comment]
Nice! Thanks @fancyremarker ... and/or incorporate into dashboard
