### ISSUE TITLE
Set git commit hash as an environment variable in apps

### ISSUE THREAD

**Issue by aaw** [aptible/support#167]
This would make things like reporting to Sentry easier.

**Comment by cancan101** [comment]
Any updates on this?

**Comment by alandotcom** [comment]
@aaw If you did not place `.git` in `.dockerignore`, then you can run `git rev-parse --short=8 HEAD` to get that info in the container.

Otherwise, you can also just unignore `.git/HEAD` and you'll find the same contents in that file.

**Comment by fancyremarker** [comment]
See `APTIBLE_GIT_REF`: https://www.aptible.com/documentation/enclave/reference/containers/environment.html?highlight=aptible_git_ref#aptible-git-ref
