### ISSUE TITLE
Sitemap not reindexing (possible Swiftype configuration issue?)

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#169]
The following article is an example of a page not being reindexed by Swiftype:

https://support.aptible.com/topics/paas/how-to-set-up-bundler-caching

It's properly inside /sitemap.xml, but not showing up in search results.

**Comment by fancyremarker** [comment]
Via Omar: another affected example: https://support.aptible.com/search/#stq=FROMCACHE&stp=1

**Comment by fancyremarker** [comment]
Here's another example of an extension of this problem:

[This page](https://support.aptible.com/topics/paas/how-to-add-internal-domain) is being indexed by the engine, even though the file has been deleted from the repo and [no longer appears in sitemap.xml](https://support.aptible.com/sitemap.xml).

There are two ways to remedy this, and we should implement both:
- [ ] Prune extraneous files on Middleman deploy
- [ ] Fix whatever is causing Swiftype not to re-index updated sitemaps

**Comment by gib** [comment]
I emailed Swiftype support on this. Their docs suggest we're doing everything correct in terms of the robots.txt and sitemap.xml files. We're not currently near any limits for our account:
- 75 of 5,000 docs
- ~2,500 queries of 10,000

**Comment by gib** [comment]
I did find a manual re-crawl and kicked that off from Swiftype.

**Comment by gib** [comment]
Swiftype support has fixed the issue. They had suggested we create a new "engine" (that's what they call a site configuration for indexing), but responded again this morning. It sounds like they had a bug in their sitemap.xml parser:

> you can still use the old engine because we've actually released a fix for that bug and the sitemap has been indexed in the old engine.

**Comment by gib** [comment]
Closing this and creating a separate issue for the file pruning.
