### ISSUE TITLE
DB Replication Burndown

### ISSUE THREAD

**Issue by wcpines** [aptible/support#182]
- [x] PostgreSQL
- [x] MongoDB
- [x] MySQL
- [x] Redis
- [x] Elasticsearch

(Closed) duplicate tickets: 
- https://github.com/aptible/docker-couchdb/issues/9
- https://github.com/aptible/docker-mongodb/issues/3

**Comment by krallin** [comment]
MongoDB is done. Elasticsearch is pending until we know if there is demand for it considering it would require a (presumably) pricey Shield license to avoid sending unencrypted replication traffic over the network.

Looks like this is complete!
