### ISSUE TITLE
clarify quickstart guides re: default vhosts

### ISSUE THREAD

**Issue by wcpines** [aptible/support#203]
We see a number of requests each month which indicate confusion over default vhosts. I think we should either clarify that these get provisioned _only_ for dev environments OR provide functionality in dashboard to create your own default vhost for prod envs.  

@fancyremarker for thoughts.

**Comment by fancyremarker** [comment]
A support article is a reasonable stopgap fix. aptible/api.aptible.com#234 covers creating one's own default VHOST from Dashboard. That is the appropriate ultimate fix.

**Comment by wcpines** [comment]
Closing in favor of product feature listed above.
