### ISSUE TITLE
Connecting to MySQL with ActiveRecord 4.2.5 requires sslcert or sslkey

### ISSUE THREAD

**Issue by skylar-anderson** [aptible/support#208]
Contrary to https://support.aptible.com/topics/troubleshooting/mysql-connection-refused/, ActiveRecord requires `sslcert` or `sslkey` to be configured in order to attempt to connect over SSL.  The only current workaround is to specify `aptible-nossl` as the user.

**Comment by wcpines** [comment]
Documented.
