### ISSUE TITLE
Minor issues: desktop layout

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#24]
- [x] Currently, all "Contact Us" links fall back to `mailto:` links. Should these be a contact form? (Maybe fine as-is.)
- [x] "Fenced" code currently overflows its div, needs scrollbar. #1 below
1. ![image](https://cloud.githubusercontent.com/assets/156030/6260970/5a85b990-b7b5-11e4-8ffb-ae7cf9ded1f3.png)

**Comment by skylar-anderson** [comment]
@fancyremarker FYI, 1 & 2 are fixed after #35 and #36

**Comment by fancyremarker** [comment]
Cool, thanks, closing.
