### ISSUE TITLE
Set APTIBLE_SSH_USER in ENV of `aptible ssh`

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#240]
This would make it easier for apps to do logging and other functions based on the Aptible user connecting via `aptible ssh`. Of course, this would NOT be sufficient for any authentication/security mechanism, since the ENV variable can be trivially overridden.

**Comment by blakewest** [comment]
:+1: this would be great! We'll use this to set our PaperTrail `whodunnit` variable.

**Comment by blakewest** [comment]
@fancyremarker hey frank, just wanted to follow up on this. Any timeline on this getting implemented?

**Comment by fancyremarker** [comment]
@blakewest: This one should be available as part of next week's release.

**Comment by EpiphanyMachine** [comment]
@fancyremarker any update on this?  Thanks

**Comment by blakewest** [comment]
@fancyremarker any update on this?

**Comment by fancyremarker** [comment]
See [Ephemeral SSH Session Logging](https://www.aptible.com/documentation/enclave/reference/apps/ssh-sessions.html#logging), now available for all Enclave environments.
