### ISSUE TITLE
docs for installing cli need to be updated

### ISSUE THREAD

**Issue by jedschneider** [aptible/support#267]
just installed the cli tool using https://support.aptible.com/topics/cli/how-to-install-cli/ but it wasn't on my path, so I did some looking and it says, counter intuitively in the source here: https://github.com/aptible/aptible-cli

> NOTE: To install the aptible tool as a system-level binary, consider using the aptible-toolbelt gem, which is performance-optimized through dependency pinning.

So I think you should probably specify, or just point to the github repo?

**Comment by fancyremarker** [comment]
Hey @jedschneider if you're not seeing `aptible` on the path, that's actually a different issue than what aptible-toolbelt is designed for (and in fact, installing aptible-toolbelt won't help at all with this particular issue).

What's your current `PATH`, and how have you installed Ruby?

**Comment by jedschneider** [comment]
installed via `gem install` under rbenv. the shims dir is on my path. didn't seem available yesterday after install even after a rehash. Maybe I had to reload my shell. Anyway, I was just pointing out the support page seems out of sync with advice on the github repo.

**Comment by jedschneider** [comment]
I should mention I have it working now. when it didn't work yesterday I just created a symlink to something else on my path and it was working but it seems to be point to the appropriate file now in the shims dir.

**Comment by fancyremarker** [comment]
For future reference for anyone landing on this ticket, the current recommended approach for installing is via the Aptible Toolbelt: https://www.aptible.com/support/toolbelt
