### ISSUE TITLE
Using upstart/similar

### ISSUE THREAD

**Issue by Ch4s3** [aptible/support#294]
Some documentation on how to monitor processes and workers and restart them when they crash would be helpful.

**Comment by krallin** [comment]
While it's true that this is something we should probably document to some extent on our end, in the meantime you might want to review Docker's documentation for process management using supervisord: https://docs.docker.com/engine/admin/using_supervisord/

**Comment by Ch4s3** [comment]
Thanks, I'll take a look.

**Comment by fancyremarker** [comment]
For anyone landing on this issue in the future, please see the documentation for Aptible Container Recovery, which is likely preferable to implementing a process monitor inside one's container: https://www.aptible.com/documentation/enclave/reference/containers/container-recovery.html
