### ISSUE TITLE
Can I run a command or SSH into my live production app containers?

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#53]
Right now, the only way to create a remote SSH session is via `aptible ssh`, which creates a new, one-time use container from your app's current configuration and image. For security reasons, this does not have access to your live app's process space.

In the future, we may support running commands against live app containers, a la `docker exec`, but that's not being contemplated currently. Leaving this issue open to address any related questions.

**Comment by wcpines** [comment]
@fancyremarker  Is this pretty much done? I'm happy to submit as a PR.

**Comment by fancyremarker** [comment]
@wcpines: This may not need an article, actually. I think I meant to leave the "question" label and remove "needs article." I'll update.

**Comment by wcpines** [comment]
10-4
