### ISSUE TITLE
How can I view open support tickets?

### ISSUE THREAD

**Issue by chasballew** [aptible/support#61]
Sign up/in at https://aptible.zendesk.com/hc/en-us/requests. You can also request permission to view all of your organization's tickets, by [sending us a note](https://support.aptible.com/contact/).

**Comment by chasballew** [comment]
@wcpines - Please draft. Thanks!

**Comment by wcpines** [comment]
@chasballew  Can we close this?

**Comment by chasballew** [comment]
Closed by #92
