### ISSUE TITLE
Add framework icons

### ISSUE THREAD

**Issue by chasballew** [aptible/support#67]
Add icons and update `data/quickstart.yml` for:
- [ ] Meteor

**Comment by wcpines** [comment]
is this outstanding? (does it matter?)

**Comment by skylar-anderson** [comment]
I think we should at least do this for the [node index page](https://support.aptible.com/quickstart/node/).

**Comment by wcpines** [comment]
~~Express~~ Meteor

**Comment by wcpines** [comment]
Can't find SVGs for Gorilla and Jersey. Meteor is [here](https://worldvectorlogo.com/logos/meteor-icon.svg).  @sandersonet I'll assign to you since I can't edit the file as needed.  Low prio.
