### ISSUE TITLE
Deploy error: "Archive::Tar::Minitar::FileNameTooLong"

### ISSUE THREAD

**Issue by ianyamey** [aptible/support#71]
Attempts to deploy to Aptible are failing with the following error:

```
Writing objects: 99% (130/131)
Writing objects: 100% (131/131)
Writing objects: 100% (131/131), 17.08 KiB | 0 bytes/s, done.
Total 131 (delta 92), reused 42 (delta 18)
remote: (8ミ | INFO: Authorizing...
remote: (8ミ | INFO: Initiating deploy...
remote: (8ミ | INFO: Deploying...
remote: INFO -- : Building app image from source...
remote: ERROR -- : Archive::Tar::Minitar::FileNameTooLong
remote: (8ミ | FATAL: Deploy failed.
```

**Comment by fancyremarker** [comment]
Thanks @ianyamey! Will add a support article for this, and also improve the error messaging on deploys.

**Comment by ianyamey** [comment]
The cause of this was a file with a very long filename in our repo.

GNU Tar will generate the above error any filename has a length of more than 100 characters (see docker/docker#7135)

Renaming this file to have a shorter filename fixed the issue.

**Tip:** To find long filenames, run: `find . -print | awk '{ print length, $0 }' | sort -rn | head -n 10` (thanks @fancyremarker)

**Comment by mmmurf** [comment]
Hello, anyone know if there is something equivalent to .slugignore on aptible?

**Comment by Ch4s3** [comment]
+1

**Comment by fancyremarker** [comment]
@mmmurf : Have you tried .dockerignore for this purpose? I need to confirm that it will fix the original `Archive::Tar::Minitar::FileNameTooLong` exception, but it is certainly useful as a way to prevent files from being added to your Docker container.

**Comment by JohnGoodman** [comment]
Hey, just got this issue. Was a fix ever implemented or that support article written?

**Comment by farmhouseinc** [comment]
+1

**Comment by krallin** [comment]
This issue should be resolved (as of several months ago — I just didn't realize this ticket existed); we're not using minitar anymore. 

Do let us know if you hit this again though!
