### ISSUE TITLE
Keep feature branches up-to-date with staging.

### ISSUE THREAD

**Issue by blakewest** [aptible/support#84]
Specifically, this could either mean us being able to create feature branches on the fly with staging data on aptible, or potentially have a way to push staging data from aptible directly to heroku would be great!

So for feature branches, this might look like... 
`aptible pg:copy $STAGING_APP_NAME::DATABASE_URL DATABASE_URL --app $APP_NAME --confirm $APP_NAME`

**Comment by chasballew** [comment]
Hey Blake, thanks! Can you elaborate a little on what happens with this command?

**Comment by blakewest** [comment]
Hey Chas,
Yeah basically, this would be a command we run anytime we spin up a new feature branch server, which we do on a daily basis. These branches represent a completely new instance of the app, but we like them to share staging data, so that we can have a realistic app to play around with for the feature. 

The command I wrote above was copying the database from staging to the new feature branch name. But maybe a better way to write that would be something like...

```
DATABASE_URL=$(bundle exec aptible db:clone $STAGING_DB_NAME ${APP_NAME}-pg)
#       echo "Postgres DB created for $APP_NAME from $DATABASE_URL"
#       bundle exec aptible config:add --app $APP_NAME DATABASE_URL=$DATABASE_URL
```

Ideally we'd like to get rid of Heroku entirely and start using aptible for spinning up feature branches, but if that can't happen, then as I said, really any easy way to potentially push data from our aptible staging DB to our Heroku would be great. It doesn't actually matter all that much what the implementation is. Does that clear things up?

**Comment by chasballew** [comment]
Yes, that's helpful, thanks! Why not just share a database?

**Comment by fancyremarker** [comment]
In case it's helpful for others landing on this issue in the future, please see ["Restore Database Backups across Environments"](https://www.aptible.com/changelog/restore-database-backups-across-environments/).
