### ISSUE TITLE
Support for generic TCP VHOSTs

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#86]

**Comment by cancan101** [comment]
Because of: https://github.com/docker/docker/issues/11185 if you are using Docker >= 1.7, I would suggest starting the daemon with `--userland-proxy=false` as it significantly reduces RAM usage.

Further, per: https://docs.docker.com/v1.7/articles/networking/#binding-container-ports-to-the-host:

> When disabled, Docker uses both an additional MASQUERADE iptable rule and the net.ipv4.route_localnet kernel parameter which allow the host machine to connect to a local container exposed port through the commonly used loopback address: this alternative is preferred for performance reason.

**Comment by fancyremarker** [comment]
See https://www.aptible.com/documentation/enclave/reference/apps/endpoints/tcp-endpoints.html
